### ISSUE TITLE
add support for proxy authentication handling

### ISSUE THREAD

**Issue by driak** [pouchdb/pouchdb-server#105]
Hi,

Would it be feasible to add proxy authentication support as is available on Couchdb through the 'httpd:authentication_handlers' configuration setting?

We're looking into using pouchdb-server instead of a Couchdb instance, but need to be able to authenticate user credentials outside of pouchdb while still allowing pouchdb update filters to be applied in order to enforce per document write authorization.

Thanks!

**Comment by marten-de-vries** [comment]
Definitely possible, but it hasn't been implemented yet by anybody as far as I know. A good example to start from would be the [dummy session handler that is used by CouchDB's test suite](https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/special-test-auth.js). Also handy as a reference is our [normal session implementation (cookie/http auth)](https://github.com/pouchdb/express-pouchdb/blob/master/lib/routes/authentication.js).

There might also be a few currently disabled tests you could reuse in [couchdb-harness](https://github.com/pouchdb/couchdb-harness).

**Comment by nolanlawson** [comment]
This is better handled by proxies on top of pouchdb-server
