### ISSUE TITLE
Request parameter on a filter function does not hold the request headers

### ISSUE THREAD

**Issue by driak** [pouchdb/pouchdb-server#106]
Hi,

The interface for a filter function in the design document receives the document together with the requests object, but on pouchdb-server the request object only seems to hold the http query parameters, not the http headers.

Couchdb does provide the header parameters in the request object.

Having the headers available on the request is useful in situations where you have an authenticating proxy as part of the general infrastructure of the environment. Typically the proxy will add an authorization header to the request when the user is successfully authenticated.

Services can then use this header info for authorization purposes.

In our specific case we use this to define a filter on Couchdb which allows the client to retrieve only the documents he owns. The filter would then compare (part of) the authorization header's user id with the owner id defined on the document itself.

------------------ update ------------------

Here's a log statement from a console.log(request) on a filter...
On the debug statements you can see the request holds several headers, but they do not appear on the request object passed to the filter (the json right after the '-----------------' line). 
(This particular filter works fine on Couchdb.)

```
[debug] 'GET' /wi-pv-data/_changes?timeout=25000&style=all_docs&filter=wi-pv-design/pvUserFilter&since=0&limit=100 {1,1} from "127.0.0.1"
[other] Headers: [{'Accept', application/json},
[other] {'Connection', close},
[other] {'Content-Type', application/json},
[other] {'Cookie', voucher=4f55459c-4f14-43bf-abd7-1941f5d5f1f7; ldapid=test1},
[other] {'Host', 127.0.0.1:9200},
[other] {'Ldapid', test1},
[other] {'User-Agent', akka-http/2.3.11},
[other] {'X-Auth-Couchdb-Roles', Editor},
[other] {'X-Auth-Couchdb-Username', test1}
_______________________
{ query:
   { timeout: 25000,
     style: 'all_docs',
     filter: 'wi-pv-design/pvUserFilter',
     since: 0,
     limit: 100 } }
undefined:1
 (d.data && d.data.gebruiker && d.data.gebruiker.ldapId && r.Headers.Ldapid) {
                                                                    ^
TypeError: Cannot read property 'Ldapid' of undefined
    at eval (eval at evalFilter (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/evalFilter.js:10:5), <anonymous>:1:183)
    at filter (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/utils.js:123:50)
    at onGetWinningDoc (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/adapters/leveldb/leveldb.js:970:15)
    at onGetMetadata (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/adapters/leveldb/leveldb.js:998:18)
    at Transform._transform (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/lib/adapters/leveldb/leveldb.js:1012:16)
    at Transform._read (/usr/local/lib/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

**Comment by marten-de-vries** [comment]
Support for filter functions (and view functions) is handled in PouchDB. PouchDB doesn't know anything about request objects. To solve this, the first step would be to make it possible to pass in a request object as some option to the PouchDB function. This could then be filled in pretty easily by express-pouchdb (the code is already there for pouchdb-validation, -show, -list & -update).

**Comment by nolanlawson** [comment]
Closing because I'm having trouble understanding what the repro steps are for this bug. Please reopen as necessary.
