### ISSUE TITLE
Errors during pouchdb test run (Possibly unhandled Error: Can't set headers after they are sent.)

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb-server#108]
So I was investigating https://github.com/pouchdb/pouchdb/issues/3989 and these errors come up consistently when running 

    $ LEVEL_ADAPTER=memdown SERVER=pouchdb-express-router GREP=2913 npm test

https://gist.github.com/daleharvey/b096bb0951b263a7525d

**Comment by nolanlawson** [comment]
That's an error with the cors proxy that I've seen many times. It's part of the reason I've wanted to get rid of the cors proxy, although for various reasons that hasn't been possible (broken integration with Saucelabs, broken cors support in Couch master, etc.).

**Comment by nolanlawson** [comment]
oh wait I don't know what I'm talking about

**Comment by nolanlawson** [comment]
fix in https://github.com/pouchdb/express-pouchdb/pull/227

**Comment by marten-de-vries** [comment]
#227 has been merged (although I did just reopen it) and I agree that we should circumvent the ``setTimeout()`` hack it removes, so this shouldn't show up again.
