### ISSUE TITLE
Stop writing stdio by default

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb-server#110]
$ SERVER=pouchdb-server npm test

Inside pouchdb shouldnt be spitting out logs of http requests

**Comment by nolanlawson** [comment]
I can't even figure out how to turn off logging anymore. Also my profiling seems to suggest that `couchdb-logger` is actually making pouchdb-server super slow.

**Comment by nolanlawson** [comment]
Okay nevermind, I figured out how to change the logging, but it didn't actually improve the performance. It was probably an artifact of the node-inspector profiler.

**Comment by nolanlawson** [comment]
Also I should admit, I actually really appreciate that pouchdb-server writes logs to stdout by default. I think it makes it easier to debug and more approachable for newbies.

However, there ought to be a setting to write ONLY to files and not to stdout. Currently it seems like to have to write both to a file and to stdout, or to neither. We should fix that.

**Comment by marten-de-vries** [comment]
a ``--no-stdout-logs`` option should be pretty easy, just adding the option & putting the call that initiates tailing the log in an ``if``-statement.

**Comment by nolanlawson** [comment]
:+1: makes sense to me, and I like that it defaults to false

**Comment by nolanlawson** [comment]
Fixed

**Comment by jmatsushita** [comment]
Is this accessible for the express version? It seems that it uses stdio by default (I see 409 errors logged on stdout/stderr - and by the way, not in the log.txt even when its enabled).
