### ISSUE TITLE
Firefox+Selenium tests error out with ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb-server#117]
As found in https://github.com/pouchdb/pouchdb/issues/4240

**Comment by nolanlawson** [comment]
I think I've found the real cause of the Selenium bug:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:2020/testdb/_changes?timeout=25000&style=all_docs&feed=longpoll&since=1&limit=100&_nonce=1441573976214. (Reason: CORS request failed).

**Comment by nolanlawson** [comment]
I also found that this is failing:

>       try {
        obj = JSON.parse(obj);
      } catch (e) {
        // Probably a malformed JSON from server
        return cb(e);
      }

**Comment by nolanlawson** [comment]
Nevermind; those are also red herrings apparently

**Comment by nolanlawson** [comment]
Actually this is a very subtle bug and I have no idea what is going wrong. But it is definitely the case that this test (`http://127.0.0.1:8000/tests/integration/index.html?grep=test.issue3179.js-http-http%20%233179%20conflicts%20synced%2C%20live%20sync`) shows a CORS warning 1) only in Firefox, and 2) only with PouchDB Server.

**Comment by nolanlawson** [comment]
OK, the CORS thing is definitely a red herring, because Firefox shows it even if you access a CORS-enabled CouchDB directly at localhost:5984.

**Comment by nolanlawson** [comment]
Not fixed yet

**Comment by nolanlawson** [comment]
fixed per https://github.com/pouchdb/pouchdb/pull/4290
