### ISSUE TITLE
open to making the server exported/importable?

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb-server#120]
Hey crew,

Is there a reason this was written exclusively to be run as an executable?  I want to import it into my script/app.  E.g. export the server in `index.js`, then the `bin.js` could run `require('./index.js`)(...)`. Let me know! Thx

**Comment by gr2m** [comment]
I'm not part of the crew, but I'd say you can use https://github.com/pouchdb/express-pouchdb, as pouchdb-server is a wrapper around that. Does that work for you?

**Comment by daleharvey** [comment]
Yup, one of the reasons for express-pouchdb vs pouchdb-server was that express-pouchdb did not depend on pouchdb itself and could be ran as part of your own app server, pouchdb-server was the standalone version

**Comment by cdaringe** [comment]
Ah, I see.  I didn't know it was a thing!  Thanks :)
