### ISSUE TITLE
Error Install pouchdb-server (windows 7)

### ISSUE THREAD

**Issue by ffle** [pouchdb/pouchdb-server#121]
Failed to install pouchdb-server in Windows 7 when issue the following command from command window:
>npm install -g pouchdb-server

It failed to find git path. I have installed git and tried again, got the same error.
It mentioned to "have git installed and in your PATH". What does it mean?

Here is part of the log:
.....
57634 verbose unlock done using C:\Users\[user name]\AppData\Roaming\npm-cache\_locks\pouchdb-server-9f488a1727b3b777.lock for C:\Users\\App[user name]Data\Roaming\npm\node_modules\pouchdb-server
57635 verbose stack Error: not found: git
57635 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:73:28)
57635 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:76:29)
57635 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:84:16
57635 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
57636 verbose cwd C:\[path]\pouchdb\pouchdb-getting-started-todo
57637 error Windows_NT 6.1.7601
57638 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "pouchdb-server"
57639 error node v4.2.1
57640 error npm  v2.14.7
57641 error code ENOGIT
57642 error not found: git
57643 error Failed using git.
57643 error This is most likely not a problem with npm itself.
57643 error Please check if you have git installed and in your PATH.
57644 verbose exit [ 1, true ]
57645 verbose unbuild node_modules\pouchdb-server\node_modules\express-pouchdb\node_modules\pouchdb-replicator\node_modules\equals
57646 info preuninstall equals@0.3.7
.......
Thanks

**Comment by robertkowalski** [comment]
that is not a problem of pouchdb itself, npm is trying to tell that you need to have git (https://git-scm.com/) installed and in your PATH (`git` commands are executable inside the terminal/shell you are using).

**Comment by nolanlawson** [comment]
Thanks for diagnosing @robertkowalski. Closing for now.
