### ISSUE TITLE
Doesn't start in admin party mode if you use --dir

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#125]
This is a nasty bug. Run it with `--dir foobar` and it will start by asking for a login/password, as opposed to without `--dir`, where it will start in admin party mode.

**Comment by marten-de-vries** [comment]
Will look into this tomorrow.

**Comment by nolanlawson** [comment]
Thanks man! :)

**Comment by marten-de-vries** [comment]
Can't reproduce I'm afraid. Something to check: by default, the config file is **not** moved into the foobar directory. Did it pick up an old one with an admin password inside?

**Comment by nolanlawson** [comment]
Maybe that's what happened. If you can't repro, then let's not worry about it.
