### ISSUE TITLE
thoughts on running programmatically?

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb-server#128]
i'm interested in firing up the server as a module as a couchdb stub for my tests.  i can definitely child-process it, but have interest in doing something like

```js
const pdbSrv = require('pouchdb-server')
pdbSrv.on('ready', handler);
pdbSrv.init({ inMem: true, noLog: true });
const handler = () => {
    setTimeout(() => { pdbSrv.kill() }, 500)
}
```

what are you general feelings towards this?

**Comment by marten-de-vries** [comment]
See the express-pouchdb project: https://github.com/pouchdb/express-pouchdb

In short, you can just spin up your own express server, and control it however you like. For programmatically killing such a server immediately (ignoring Keep-Alive connections), you can use https://www.npmjs.com/package/killable , which I wrote for that purpose and pouchdb-server also uses internally.

PouchDB-Server is (almost) just a front-end that controls express-pouchdb, and as such, a programmatic API doesn't make much sense.

**Comment by cdaringe** [comment]
you know, embarrassingly, i think i may have already asked this very question before.  your response is all too familiar.  thanks for the quick reply!
