### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by SukantGujar** [pouchdb/pouchdb-server#136]
Hi,

I have come into sort of a corner trying to use the very cool pouchdb-find with superlogin. The problem is that for both pdb-find and superlogin, the only common remote backend is pouchdb-server. Actually there's Cloudant as well, but it being cloud based, is not a choice for me.

So I wanted to quickly check with you that although termed "quick and dirty" CouchDB replacement, would pouchdb-server be reliable enough to power a simple (roughly thousand user) back-end? I am not talking about a heavy traffic site. What are the limits to which I can take it?

Thanks!
Sukant

**Comment by nolanlawson** [comment]
I am one of the primary authors of this project, and I would currently not advise it for production use. Nearly everything it can do, CouchDB can do better/faster.

pouchdb-find will be available as "Mango" in CouchDB 2.0, which is already in alpha and soon to be released. If you'd like to check it out, it's here:   https://docs.google.com/document/d/1BtndYr-0KDQTqBSLVdJoR_8C5ObYjT1RBo_Qyh5ykdQ/edit#

**Comment by nolanlawson** [comment]
That said, I do think this is a great project for testing/debugging/developing/etc. I just wouldn't use it in any scenario where you could use CouchDB instead. CouchDB is more battle-tested and feature-complete.

**Comment by SukantGujar** [comment]
Thanks for your response. It is indeed very useful for what it does.
Regards,
Sukant
On Apr 21, 2016 7:27 PM, Nolan Lawson <notifications@github.com> wrote:That said, I do think this is a great project for testing/debugging/developing/etc. I just wouldn't use it in any scenario where you could use CouchDB instead. CouchDB is more battle-tested and feature-complete.

**Comment by Brainsway-Cloud** [comment]
Nolan. Is this still the state of things or is there a proven production quality server option for Pouch other than CouchDB? Would any of the LevelUP backends be considered production quality for server?

**Comment by SukantGujar** [comment]
@Brainsway-Cloud Now that CouchDB 2.0 is out for quite a while, are there any other use cases you have where you need to fall back to pouchdb-server? Asking out of curiosity, my requirement was the ease of Mango queries. tia!

**Comment by Brainsway-Cloud** [comment]
@SukantGujar -- I was hoping for a production quality adapter to an AWS DBaaS to avoid the need to administer the couchdb server. Maybe even figure a way to run Pouch serverless on AWS Lambda.
