### ISSUE TITLE
Fails on Node >= 6.0

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [pouchdb/pouchdb-server#137]
This is not your issues but wanted to make you aware. I have opened a issue on couchdb-harness recommending they upgrade to glob to 3.2.4 or higher.

`-- pouchdb-server@1.1.1
  -- couchdb-harness@0.1.6
    -- glob@3.1.21
      -- graceful-fs@1.2.3 **<-- fails on node 6.0**
`

**Comment by nolanlawson** [comment]
should be fixed now
