### ISSUE TITLE
Why doesn't the NPM version of pouchdb-server contain test-*ouchdb.sh?

### ISSUE THREAD

**Issue by yaronyg** [pouchdb/pouchdb-server#138]
I was running the tests on express-pouchdb and it wants to call the NPM script command test-couchdb inside of pouchdb-server. But the command was failing because the bin directory in pouchdb-server didn't contain test-couchdb.sh (or test-pouchdb.sh). It only contained pouchdb-server. I did a clean install of just pouchdb-server from NPM and sure enough the bin directory doesn't contain the test-*.sh files. What's going on?

**Comment by garrensmith** [comment]
Its just a matter of appending the required files [here](https://github.com/pouchdb/pouchdb-server/blob/master/package.json#L47

**Comment by garrensmith** [comment]
@yaronyg I've pushed a new version of pouchdb-server that now works with pouchdb 5.4. I'm not sure about having the `test-pouchdb.sh` and `test-couchdb.sh` in the deploy. Shouldn't we just keep that in the repo. @nolanlawson what are your thoughts?

**Comment by nolanlawson** [comment]
Those should not be in the deploy, yeah. If express-pouchdb needs those for testing, then it should either do a `git clone` or it should (ideally) become part of the pouchdb-server monorepo.

**Comment by nolanlawson** [comment]
This is a deliberate move; we don't publish our tests on npm.
