### ISSUE TITLE
Pass other options to pouch

### ISSUE THREAD

**Issue by fcasarsasolari** [pouchdb/pouchdb-server#141]
Hi,

i have a _LOT_ of data that frequently will be deleted and I would like to get rid of the old revisions.

How can I pass custom db options such as: `{revs_limit: 1, auto_compaction: true}` to the opening of the DB?

I have tryed to do this curl -X PUT -d "1" http://localhost:5984/bulktest/_revs_limit but does not work as in couch. [LINK](http://wiki.apache.org/couchdb/HTTP_database_API#Accessing_Database-specific_options)

Thanks.

**Comment by nolanlawson** [comment]
Unfortunately you cannot. Currently you would need to either fork this project
or use express-pouchdb directly.

**Comment by nolanlawson** [comment]
this is out-of-scope for pouchdb-server
