### ISSUE TITLE
Replication with credentials does not supported? 

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb-server#145]
How can we create a replication task between local instance and remote one which we login with credentials?

**Comment by nolanlawson** [comment]
In principle pouchdb-server should work exactly the same as CouchDB 1.x, hence you can use something like https://github.com/nolanlawson/pouchdb-authentication for this.

In practice, I don't actually know how much of the credentials API that pouchdb-server supports. Keep in mind that pouchdb-server is mostly intended for quick debugging and unit tests, and not for production environments.

**Comment by ceremcem** [comment]
No problem, I don't expect any performance from pouchdb-server. My only purpose is using pouchdb-server for quick start-ups for our scada system and using it for backup media of production systems. 

By the way, I created a replication document in `_replicator` db by passing credentials in url, like so: 

```
{
  "_id": "197d5186-402d-4de4-8d4b-d3acf90157b7",
  "source": "https://theadmin:theadminpassword@example.cloudant.com/sourcedb",
  "target": "yourtargetdb",
  "create_target": true,
  "continuous": true,
}
```
All replication went well.
