### ISSUE TITLE
License info mismatch

### ISSUE THREAD

**Issue by rkozhikk** [pouchdb/pouchdb-server#146]
The LICENSE file changed from MIT to Apache License 2.0 in the 0.7.0 release, but the README, from version 0.7.0 to the current version, continues to include the following:

> License
> 
> The MIT License. See the LICENSE file for more information.

 If the intent was to use Apache License 2.0, can we please have the README updated? 

Thanks again for the awesome work, it's much appreciated!

**Comment by nolanlawson** [comment]
Yes, you're right, could you file a PR updating to Apache please? :D

**Comment by nolanlawson** [comment]
fixed
