### ISSUE TITLE
replication from a remote CouchDB does not trigger _changes feed

### ISSUE THREAD

**Issue by ceremcem** [pouchdb/pouchdb-server#148]
My web application (uses pouchdb) is connected to pouchdb-server in my localhost. My pouchdb-server is replicating from a remote couchdb database (cloudant) in continuous mode. Any changes made by localhost:.../_utils interface is reflected to my application immediately but making a modification in a document in the remote database does not seem to trigger _changes feed, although the change is replicated to local pouchdb-server. I can see the changes if I refresh my page in my application.

**Comment by nolanlawson** [comment]
Can you provide a test case to reproduce? Also please keep in mind that pouchdb-server is not meant for production scenarios, but only for quick debugging. It's known to not be as complete as CouchDB.

**Comment by ceremcem** [comment]
Sorry, it's my bad. I checked via  `curl -X GET http://localhost:5984/mydb/_changes?feed=continuous` and changes seem to be propogated correctly. It should be something with my application.
