### ISSUE TITLE
Sync what I have, but don't get new documents (unidirectional)

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb-server#151]
I have a local pouchdb-server that syncs with a few offline devices.

The goal is to purge the database every month since a LOT of data goes into it. I'd like to sync the server with the offline devices but only send data OUT to the cloud database not bring it back in.

Is that possible?

**Comment by nolanlawson** [comment]
Unfortunately pouchdb does not support purge. You will need to periodically use filtered syncing to sync the documents you want to keep into another database.

**Comment by bgold0** [comment]
@nolanlawson Is it possible to have a cron on the pouchdb-server to delete documents older then a specific time?

**Comment by nolanlawson** [comment]
Sure, you can write a cron to do this, absolutely.

**Comment by nolanlawson** [comment]
Closing old issues, please reopen as necessary
