### ISSUE TITLE
Continuous Replication Not listed / can't see status

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb-server#152]
When I add a continuous replication to or from a database in PouchDB Server it says it has begin with the green tab at the top but I don't see anything in the Active Tasks.

Also, when I lose connection, the replication seems to become void and stops entirely even when I restart the database.

Is that what is supposed to happen? Is there anyway to see that a replication is active and is there anyway to make it so a replication stays reactive and resumes once a connection is back up?

**Comment by nolanlawson** [comment]
I believe this has been broken for awhile. We need to update to latest Fauxton.

**Comment by nolanlawson** [comment]
Fixed in latest fauxton now
