### ISSUE TITLE
413 the request entity is too large

### ISSUE THREAD

**Issue by bgold0** [pouchdb/pouchdb-server#153]
My document I am trying to replicate to my cloud server has attachments equaling 0.9mb+1.3mb (2.2MB). When I try to replicate the database to the cloud, I get the following error:

> {"error":"too_large","reason":"the request entity is too large","status":413,"name":"too_large","message":"the request entity is too large","result":{"ok":false,"start_time":"2016-10-05T19:38:11.441Z","docs_read":1,"docs_written":0,"doc_write_failures":1,"errors":[],"status":"aborting","end_time":"2016-10-05T19:38:12.195Z","last_seq":31}}

I am using the default pouchdb-server options. Does anyone know what I can do to fix this?

**Comment by mohlsen** [comment]
This might not be so much of an issue with pouch / pouchdb-server, but a limit on your hosting provider's web server.  Are you hosting your node.js app right on the wire, or is it sitting on top of another web server?

From the Error, it looks like you might be on Azure? (which means IIS is hosting Node.js)  If so, check out the maxRequestLength setting that can be changes i the web.config.

**Comment by bgold0** [comment]
Hi @mohlsen thank you for your quick response.

I'm actually not on any server. I am on my OS X and installed node.js with npm and then just installed and ran the pouchdb server as in the instructions. I really haven't done much else.

**Comment by mohlsen** [comment]
Take a look at `express.bodyParser({limit: '5mb'})`.

http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large

**Comment by nolanlawson** [comment]
Looks like this is fixable in userland, closing
