### ISSUE TITLE
Benchmarks vs CouchDB?

### ISSUE THREAD

**Issue by ronag** [pouchdb/pouchdb-server#154]
Are there any benchmarks that can give any hints in regards to performance differences?

**Comment by nolanlawson** [comment]
pouchdb-server is much slower in my own tests, around 2x slower than CouchDB.

**Comment by rrubio** [comment]
Hi Guys,

Excuse my ignorance.. Why would we use pouchdb-server over couchdb? I'm new to this stack and slightly confused.

**Comment by nolanlawson** [comment]
Easy to run/deploy. Good for unit tests or quick development.

**Comment by nolanlawson** [comment]
Closing, it would be great if someone ran benchmarks but no one has AFAIK.
