### ISSUE TITLE
sqlite and leveldown should be optional deps

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#158]
From playing with Windows / BashOnWindows I can see this is still a problem. Since you can always run pouchdb-server in `--in-memory` mode, we should make these two deps optional and then warn if the `require()` fails and offer workarounds. E.g. "sqlite not successfully installed on your system, please try the default leveldown or --in-memory instead"

**Comment by nolanlawson** [comment]
fixed in https://github.com/pouchdb/pouchdb-server/pull/159

**Comment by albertosantini** [comment]
Just a note.

Executing `npm install pouchdb-server` (2.3.7), I see npm trying to install  `leveldown` and `sqlite3`.

Better the command `npm install pouchdb-server --ignore-scripts`.
