### ISSUE TITLE
Post to /_bulk_docs gives error

### ISSUE THREAD

**Issue by zztop101** [pouchdb/pouchdb-server#161]
Hi,
I am trying to do a post to bulk docs and I get an error "Missing JSON list of docs". Same Post works ok to CouchDB.

```javascript
      this.options.url += '/_bulk_docs';
      this.options.body = '{"docs":[{"_id":"10000","name":"Marlen Gutmann"}]}'
      rp({ url: this.options.url, method: 'POST', body : this.options.body }).then(res => {
          console.log(res);
      }).catch(err => {
          console.log('cannot do bulk post:', err)
      })
````

  gives me the err:

cannot do bulk post: { StatusCodeError: 400 - "{\"error\":\"bad_request\",\"reason\":\"Missing JSON list of 'docs'\"}\n"

from package.json:
    "pouchdb-server": "2.0.1",

Any ideas ?

**Comment by nolanlawson** [comment]
Are you sending `content-type:application/json` as a header?

Also FWIW our usual policy is that if CouchDB supports it, PouchDB supports it. Can you check if CouchDB supports the same pattern?

**Comment by nolanlawson** [comment]
You must set a content-type:application/json for posts
