### ISSUE TITLE
Does pouchdb-server support https / ssl / tls?

### ISSUE THREAD

**Issue by jmcclelland** [pouchdb/pouchdb-server#169]
Instructions for implementing https for coucdb [indicate settings that belong in the .ini files](http://docs.couchdb.org/en/2.0.0/config/http.html#secure-socket-level-options) but I'm not sure how that translates in pouchdb-server.

**Comment by jmcclelland** [comment]
It would be nice to use pouchdb-server directly... but if that doesn't work, I am able to proxy via an https connection provided by apache with:

```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^pouchdb\.your\.domain\.net$
RewriteRule /(.*) http://127.0.0.1:31868/$1 [P]
```

**Comment by nolanlawson** [comment]
We have no plans to support this inside of pouchdb-server. You might want to try https://caddyserver.com

**Comment by MerovingianByte** [comment]
@nolanlawson https is an essential feature. Why would I use pouchdb-server instead of couchdb without it? I don't mean to bash, it's a legitimate question. I like the ease of use of this app along with pouchdb, but without https...I'm not going to install something else to get https when couchdb already supports it.

**Comment by rmisio** [comment]
I'm also in need of having to communicate to the pouch db server securely. One thing I can't wrap my head around is that I believe there's two way communication with your app and the db server. You sync your data changes to the server via HTTP calls, but also changes on the db-server get synced back to your app.

I don't know the architecture of how the server communicates back to the app, whether it's sockets or something else. Anyhow, I understand how a simple proxy would help with communication from the app to the server, but I'm not seeing how it would handle the reverse.

@nolanlawson How does the database server communicate back to your app? Does it use sockets? If so, would we need our proxy to proxy that communication back to your app?
