### ISSUE TITLE
fauxton add new document fails

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#186]
_From @cdaringe on May 24, 2016 3:50_

hello:

adding a document via fauxton fails w/ express-pouchdb@latest.

on clicking "+ New Doc", a `GET http://myhost/_uuids?count=1` and fails w/ `404`

<img width="1374" alt="screen shot 2016-05-23 at 9 46 22 pm" src="https://cloud.githubusercontent.com/assets/1003261/15491680/2f48c25a-2130-11e6-9b1e-2f5f18e817af.png">

^^ the spinner spins'n'spins

node 6.2.x

_Copied from original issue: pouchdb/express-pouchdb#321_

**Comment by nolanlawson** [comment]
this works now

**Comment by cdaringe** [comment]
whoo hoooo
