### ISSUE TITLE
Can’t configure DB file location

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#189]
_From @swashcap on August 25, 2016 17:44_

OS: OS X 10.11.6
Node: v6.3.1
express-pouch: 1.0.7

Problem: I want to run an Express PouchDB server programmatically, in memory, for testing. Ideally, this does’t save _any_ files (see #303). In the mean time, it would be great to shove everything in a temporary directory and `rm -rf` it at the end of testing. Here’s my setup, which [closely mirrors pouchdb-server](https://github.com/pouchdb/pouchdb-server/blob/cf0a0280101ce313695101f1fb3eecf9e519db94/bin/pouchdb-server):

``` js
'use strict';

const express = require('express');
const expressPouchDB = require('express-pouchdb');
const memdown = require('memdown');
const path = require('path');
const PouchDB = require('pouchdb-node');

PouchDB.defaults({
  db: memdown,
  prefix: path.resolve(__dirname, '.tmp') + path.sep,
});

module.exports = function getPouchDBExpressApp() {
  const app = express();

  app.use('/', expressPouchDB(PouchDB));

  return app;
};
```

Unfortunately, database directories _aren’t saved to .tmp!_ Any thoughts?

_Copied from original issue: pouchdb/express-pouchdb#363_

**Comment by nolanlawson** [comment]
_From @DQvsRA on January 28, 2017 22:37_

Just use:
POUCHDB.defaults(
{
    prefix: './db/'
});
And make sure that this folder exists.

**Comment by nolanlawson** [comment]
This seems solvable with express-pouchdb

**Comment by flamusdiu** [comment]
@nolanlawson this must be broken. No matter what I put for the prefix for express-pouchdb it doesn't work. It always uses cwd. It started the express server just fine but I really don't want extra files/folders in my root of my project. =(

**Comment by vinz243** [comment]
@flamusdiu I made the same mistake as you. You had to configure it like this:

```js
this.app.use('/database', expressPouchDB(PouchDB.defaults({
    prefix: './database/',
})));
```

**Comment by flamusdiu** [comment]
@vinz243 Ooo, that worked! Thanks! How the heck did you figure that out?

@nolanlawson umm, this doesn't match the setup examples.

**Comment by vinz243** [comment]
I read it twice and I noticed it was:
```js
POUCHDB.defaults(
{
prefix: './db/'
});
```

And not:

```js
expressPouchDB(
{
prefix: './db/'
});
```

**Comment by flamusdiu** [comment]
I thought it was 
```
Pouchdb.defaults( {prefix: './db/'} ));
expressPouchDB(Pouchdb);
```

Not really clear having to do the defaults inside the expressPouchDB function. =\
