### ISSUE TITLE
Upgrade to latest PouchDB test suite

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#211]
We had to pin the PouchDB git commit in order to fix #207 (see #208). Ideally we should test PouchDB Server against the latest version of the test suite, though, and I have no idea why the current commit ( https://github.com/pouchdb/pouchdb/commits/ea5663679a276ffbd538814a1802be249e8b4fa5 ) is broken.

**Comment by loic** [comment]
I believe this ticket can be closed now. https://github.com/pouchdb/pouchdb-server/commit/e666451da67e3b16143ab6d375d236c99fa9dae7 pins the commit to the release commit of the latest stable release of `pouchdb` (which the `pouchdb-server` now depends on).

**Comment by marten-de-vries** [comment]
Agreed.
