### ISSUE TITLE
how can I run pouchdb server on boot?

### ISSUE THREAD

**Issue by megaed** [pouchdb/pouchdb-server#219]
This isn't exaclt an error but I have been having trouble trying to figure out how to run pouch db on boot using pm2.

**Comment by garrensmith** [comment]
I don't really know pm2. I would imagine you just tell it to run pouchdb-server with your config options. Otherwise https://github.com/pouchdb/pouchdb-server/blob/master/packages/node_modules/pouchdb-server/bin/pouchdb-server and this should help https://github.com/pouchdb/pouchdb-server/blob/master/bin/express-pouchdb-minimum-for-pouchdb.js

**Comment by garrensmith** [comment]
If you do figure it out. It would be great if you could add a section to the Readme on how to do this.

**Comment by megaed** [comment]
Thanks for the links! I ended up figuring it out.

pm2 makes the whole startup on boot thing easier. 

```
Here's what I did, I had to find the global directory to locate the pouchdb server folder which looks something like this for me since I used nvm to install node on my raspberry pi

/home/ {user} /.nvm/versions/node/v7.6.0/lib/node_modules/pouchdb-server/

I knew that I needed to do that first to be able to make pouchdb-server work but it was the links that you sent me that helped me find the index.js which is what pm2 needs to execute the node.js script on boot. So all I needed to do was point pm2 to this file along with it's absolute path.

/home/ {user} /.nvm/versions/node/v7.6.0/lib/node_modules/pouchdb-server/lib/index.js

so the command should look like this: 

pm2 start /home/ {user} /.nvm/versions/node/v7.6.0/lib/node_modules/pouchdb-server/lib/index.js

the problem now is that I can't really access the --host command to bind it to the ip I want which lead me to using the configuration option on pouchdb-server to bind it by default to my desired ip.

```
I guess this could also be done using cron to run a script on boot. 

Thanks again for the quick response!

**Comment by habeelkhan** [comment]
curl -X PUT http://localhost:5984/_config/httpd/bind_address -d '"0.0.0.0"'
