### ISSUE TITLE
jest is a production dependency for express-pouchdb

### ISSUE THREAD

**Issue by kenshyx** [pouchdb/pouchdb-server#412]
This PR https://github.com/pouchdb/pouchdb-server/pull/408 needs to be merged  since the `random-uuid-v4 v0.0.8` doesn't have this patch https://github.com/leahciMic/random-uuid-v4/pull/4

**Comment by garethbowen** [comment]
@kenshyx I think the jest dependency is fixed by https://github.com/pouchdb/pouchdb-server/commit/ac3dd6b0c25416aeeabf96609806537073426de4

I merged it recently but I haven't got around to releasing pouchdb-server yet. I'm hoping to get to it soon...

**Comment by garethbowen** [comment]
Released. Let me know if you have any issues.
