### ISSUE TITLE
Add a --proxy feature to proxy to remote DB

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-server#67]
In some cases it may be neat to be able to proxy PouchDB Server to another database using the `'http'` adapter. E.g. for the Couchbase Sync Gateway, there's no Futon/Fauxton UI, but if you could do something like:

```
pouchdb-server --proxy http://localhost:4984 -p 6984
```

Then you could use the Fauxton UI normally at http://localhost:6984/_utils.

**Comment by marten-de-vries** [comment]
Fixed: 3f14cb55a22a2cbd6faa5879fbf8ed080ffe7de3
