### ISSUE TITLE
does not throw error when port is in use

### ISSUE THREAD

**Issue by calvinmetcalf** [pouchdb/pouchdb-server#68]
I have couchdb running at 5984, I start pouchdb-server

Expected: 

It should expload

Actual: 

It pretends to work (but won't until you turn off couchdb)

**Comment by marten-de-vries** [comment]
pouchdb-server by default binds to 127.0.0.1 now like CouchDB, that might make the chances of this happening by default smaller. (Based on the comment of @calvinmetcalf).

Never managed to reproduce this myself.

**Comment by cristianszwarc** [comment]
long shot, but could be that @calvinmetcalf has configured his localhost domain with another ip other than 127.0.0.1? that would allow to open the port in a different interface? anyway, looks safe to close this issue (I just came here to check how active this project is :+1: )

**Comment by nolanlawson** [comment]
Throws an error for me, but seems to depend on the OS.
