### ISSUE TITLE
error when visit http://localhost:5984/_utils

### ISSUE THREAD

**Issue by aredo** [pouchdb/pouchdb-server#88]
after install couchdb and pouchdb-server, i try to running the pouchdb-server. but when i open the site `http://localhost:5984/_utils` i got errors.
this the screenshot
![screen shot 2015-01-05 at 1 38 16 pm](https://cloud.githubusercontent.com/assets/201664/5609986/623f5436-94e0-11e4-8b94-27e8d31c7b82.png)

**Comment by nolanlawson** [comment]
That's because you are using an older version of Express. We only support Express 4+.

**Comment by nolanlawson** [comment]
Ah crap, we forgot to republish pouchdb-server. Hang on, will fix.

**Comment by nolanlawson** [comment]
Please `npm install -g pouchdb-server` and try again. It's working for me now. Thanks for reporting!

**Comment by aredo** [comment]
hi @nolanlawson thanks. its working now.

**Comment by JG40** [comment]
> after install couchdb and pouchdb-server, i try to running the pouchdb-server. but when i open the site `http://localhost:5984/_utils` i got errors.
> this the screenshot
> ![screen shot 2015-01-05 at 1 38 16 pm](https://cloud.githubusercontent.com/assets/201664/5609986/623f5436-94e0-11e4-8b94-27e8d31c7b82.png)
