### ISSUE TITLE
Instructions to retry leveldown install

### ISSUE THREAD

**Issue by nickcolley** [pouchdb/pouchdb-server#90]
I tried doing `npm install -g pouchdb-server && pouchdb-server` and I get `Possibly unhandled Error: leveldown not available (specify another backend using the 'db' option)` since it didn't download leveldown (windows), what's the best way to retry this?

:sheep:

**Comment by marten-de-vries** [comment]
Probably something like:
``
npm install -g sqldown (or leveldown-prebuilt/medeadown)
pouchdb-server --level-backend sqldown (or one of the others)
``

The last setting can also be made permanent by setting the /_config/pouchdb_server/level_backend setting so it ends up in config.json and doesn't have to be specified all the time at start.

**Comment by nickcolley** [comment]
We have pre-builds now I think.

**Comment by SatyajitKumar** [comment]
Hi All,
I am stucking since from 2 days on this above issue. In my system not able to install 'leveldown' package. So could any one tried with alternate like : specify another backend using the 'db' option ? please suggest its a show stopper......Thanks in Advanced..

Regards
Satyajit

**Comment by nolanlawson** [comment]
`pouchdb-server --sqlite` or `pouchdb-server --in-memory` should work.

**Comment by SatyajitKumar** [comment]
Thanks nolan u r gems; however i resolved by installing SDK 1.8 for windows, by which i was able to install 'leveldown' and after that it works normally. 

However i want to see/visualize/realise the PouchDB offline sync through some webapplication with Couch database. and Is there any specific difference between pouchDB, Couch DB, Couch DB Server, pouch/couch lite, Pouch/Couch DB sync gateway etc. and what option will be best for which kind of application(mobile app, web apps..etc) ?

**Comment by nolanlawson** [comment]
Glad to know it worked! The best way to visualize this data is through the Fauxton/Futon interface, i.e. replicating to CouchDB or PouchDB Server and then opening up `/utils`.

**Comment by SatyajitKumar** [comment]
Hi Nolan,

Do you have any Java client code which can create database Instance, document, map-view and document retrieval etc. ? Thanks in advanced.

**Comment by nolanlawson** [comment]
No, sorry.
