### ISSUE TITLE
Make databases interchangeable with other PouchDBs on the filesystem

### ISSUE THREAD

**Issue by drschwabe** [pouchdb/pouchdb-server#95]
It would be cool if pouchdb-server could read/modify an existing database created by [pouchdb](https://github.com/pouchdb/pouchdb) (node)

(ie- so you can quickly spin up a pouchdb-server on any of your filesystem based PouchDB databases)

I tried adding a node pouchdb created database folder to a pouchdb-server directory but it doesn't get included in the database list; the only databases showing up in Fauxton are those created in pouchdb-server :/

The closest I got was if you create a database in pouchdb-server's Fauxton, and then delete the contents of that databases's folder - and replace with an existing pouchdb (ie- created elsewhere in node) then the pouchdb-server will read it - but it can't modify or create new docs.

**Comment by nolanlawson** [comment]
You can do this if you create the database `foo` in pouchdb-server and then copy the files over from the old `foo` folder. I agree it's not ideal though.

**Comment by mrschwabe** [comment]
Thanks, that works kind of.  I found that if you create the original database in pouchdb-server/Fauxton as you suggested you can include it in your node application (ie- var db = new PouchDB('/path/to/mydb-also-running-pouchdb-server')) and changes you make will affect the db.  However, it doesn't seem to work both ways reliably - more often than not, changes done via pouchdb-server/Fauxton on the same database will not apply.

**Comment by nolanlawson** [comment]
Yeah, if you try to use two separate processes to modify the same files, you will get wonkiness. Best to embed express-pouchdb in your app at that point.
